language: node_js

node_js:
  - 14

branches:
  only:
    - master

script:
  - echo "build"

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      branch: master

before_deploy:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv
    -in .npmrc.enc -out .npmrc -d
