language: node_js

node_js:
  - 14

branches:
  only:
    - master

script:
  - echo "build"

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      branch: master